CREATE TABLE IF NOT EXISTS GEBRUIKER (
  GebruikerID INT AUTO_INCREMENT PRIMARY KEY,
  Inlogcode VARCHAR(64) NOT NULL UNIQUE,
  Rol VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS KLAS (
  KlasID INT AUTO_INCREMENT PRIMARY KEY,
  Klasnaam VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS FOTO (
  FotoID INT AUTO_INCREMENT PRIMARY KEY,
  Bestandsnaam VARCHAR(255) NOT NULL,
  UploadDatum DATE NOT NULL,
  KlasID INT NOT NULL,
  UploaderID INT NOT NULL,
  CONSTRAINT fk_foto_klas FOREIGN KEY (KlasID) REFERENCES KLAS(KlasID),
  CONSTRAINT fk_foto_uploader FOREIGN KEY (UploaderID) REFERENCES GEBRUIKER(GebruikerID)
);

CREATE TABLE IF NOT EXISTS STUDENT (
  StudentID INT AUTO_INCREMENT PRIMARY KEY,
  GebruikerID INT NOT NULL UNIQUE,
  KlasID INT NULL,
  Naam VARCHAR(120) NOT NULL,
  Bio TEXT NULL,
  ProfielfotoUrl VARCHAR(500) NULL,
  CONSTRAINT fk_student_gebruiker FOREIGN KEY (GebruikerID) REFERENCES GEBRUIKER(GebruikerID),
  CONSTRAINT fk_student_klas FOREIGN KEY (KlasID) REFERENCES KLAS(KlasID)
);

INSERT INTO KLAS (Klasnaam) VALUES ('BEROEPS2'), ('BEROEPS3'), ('BEROEPS4')
ON DUPLICATE KEY UPDATE Klasnaam = VALUES(Klasnaam);

INSERT INTO GEBRUIKER (Inlogcode, Rol) VALUES ('ADMIN', 'admin'), ('TEST', 'user')
ON DUPLICATE KEY UPDATE Rol = VALUES(Rol);

